name: Deploy to VPS

on:
 push:
  branches:
  - main

jobs:
 deploy:
  runs-on: ubuntu-latest


  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install dependencies
    run: npm install

  - name: Build project
    run: npm run build


  # ✅ Upload fresh build
  - name: Copy dist to server
    uses: appleboy/scp-action@master
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      port: ${{ secrets.SSH_PORT }}
      source: "dist/"
      target: "/var/www/html"

  # ✅ Fix permissions
  - name: Set permissions
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      port: ${{ secrets.SSH_PORT }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      script: |
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 755 /var/www/html

        sudo systemctl restart nginx || true
        sudo systemctl restart apache2 || true

        echo "Deployment complete."

